//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BraftonView.Brafton_Importer_Clean
{

    public partial class DesktopModules_Brafton_View2
    {
        /// <summary>
        /// rptItemList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptItemList;

        protected global::System.Web.UI.WebControls.Label currentPortalID;

        protected global::System.Web.UI.WebControls.Label currentTabID;

        protected global::System.Web.UI.WebControls.Label boolFriendURL;

        protected global::System.Web.UI.WebControls.Label boolBlogModule;

        protected global::System.Web.UI.WebControls.Label boolBlogCreated;

        protected global::System.Web.UI.WebControls.Label boolCheckUrl;

        protected global::System.Web.UI.WebControls.Label boolCheckAPI;

        protected global::System.Web.UI.WebControls.Label boolCheckBlogID;

        protected global::System.Web.UI.WebControls.TextBox baseURL;

        protected global::System.Web.UI.WebControls.Literal baseURLLabel;

        protected global::System.Web.UI.WebControls.Literal apiURLLabel;

        protected global::System.Web.UI.WebControls.TextBox apiURL;

        protected global::System.Web.UI.WebControls.TextBox archiveURLLabel;

        protected global::System.Web.UI.WebControls.TextBox archiveURL;

        protected global::System.Web.UI.WebControls.DropDownList blogIdDrpDwn;

        protected global::System.Web.UI.WebControls.PlaceHolder setAPIPH;

        protected global::System.Web.UI.WebControls.PlaceHolder setARCHIVES;

        protected global::System.Web.UI.WebControls.Literal currentBlogID;

        public global::System.Web.UI.WebControls.CheckBox InclUpdatedFeedContent;

        public global::System.Web.UI.WebControls.CheckBox InclVideo;

        protected global::System.Web.UI.WebControls.Literal checkedStatusLabel;

        protected global::System.Web.UI.WebControls.Button Import;

        protected global::System.Web.UI.WebControls.Button ShowGlobals;

        protected global::System.Web.UI.WebControls.Button SaveSettings;

        protected global::System.Web.UI.WebControls.PlaceHolder nextStep;

        protected global::System.Web.UI.WebControls.PlaceHolder VideoSettings;

        protected global::System.Web.UI.WebControls.PlaceHolder CurrentVidSetting1;

        protected global::System.Web.UI.WebControls.PlaceHolder CurrentVidSetting2;

        protected global::System.Web.UI.WebControls.PlaceHolder CurrentVidSetting3;

        protected global::System.Web.UI.WebControls.PlaceHolder ArticlePlaceHolder;

        protected global::System.Web.UI.WebControls.PlaceHolder VideoPlaceHolder;

        protected global::System.Web.UI.WebControls.Label labelError;

        public global::System.Web.UI.WebControls.Literal errorCheckingLabel;

        public global::System.Web.UI.WebControls.Literal globalErrorMessage;

        protected global::System.Web.UI.WebControls.TextBox VideoPublicKey;

        protected global::System.Web.UI.WebControls.TextBox VideoSecretKey;

        protected global::System.Web.UI.WebControls.TextBox VideoFeedNumber;

        protected global::System.Web.UI.WebControls.TextBox VideoBaseURL;

        protected global::System.Web.UI.WebControls.TextBox VideoPhotoURL;

        public global::System.Web.UI.WebControls.Literal currentVideoBaseURL;

        public global::System.Web.UI.WebControls.Literal currentVideoPublicKey;

        public global::System.Web.UI.WebControls.Literal currentVideoSecretKey;

        public global::System.Web.UI.WebControls.Literal currentVideoFeedNumber;

        protected global::System.Web.UI.WebControls.Button setVidSettings;

        protected global::System.Web.UI.WebControls.Button updateVidSettings;

        protected global::System.Web.UI.WebControls.RadioButtonList RadioButtonList1;
    }
}

